"""Parser for INTEDE (Interactome of Drug-Metabolizing Enzymes).

Builds one document per Drug-Metabolizing Enzyme (DME), aggregating four
independent interaction layers from INTEDE's bulk-download files:

  - xenobiotic_interactions : drugs/xenobiotics that induce or inhibit the DME
    (from P1-02-1-INTEDE_XEOTIC_DME_Interaction.txt)
  - microbiome_interactions : gut-microbiome species that further metabolize
    a drug metabolite generated by the DME
    (from P1-01-1-INTEDE_MICBIO_DME_Interaction.csv)
  - host_protein_interactions : transcription factors / oligomerization
    partners / non-coding RNAs / histone modifiers that regulate the DME
    (from P1-03-1-INTEDE_HOSPPI_DME_Interaction_TF&Oligomerization&ncRNA&Histone_Modification.txt)
  - methylation_interactions : disease-associated DME promoter methylation
    (case vs. health/adjacent/other tissue), ICD-11 coded
    (from P1-03-2-INTEDE_HOSPPI_DME_Interaction_DNA_Methylation.txt)

DME identity (uniprot / gene_id / ec_number) comes from
P2-04-1-INTEDE_DME_Cross_Matching_ID.txt.

INTEDE's .txt files use a "long" key-value-per-line format rather than a
normal table:

    <DME_ID>\t<KEY>\t<VALUE>                                  (top-level attribute)
    <DME_ID>\t<MARKER>\t<SUB_ID>\t<KEY>\t<VALUE>               (nested sub-entity attribute)

e.g.:
    DME0001    DME___ID    DME0001
    DME0001    DME_NAME    Cytochrome P450 3A4 (CYP3A4)
    DME0001    XEOTICID    XEO00001    XEO_NAME    Dimethyl sulfoxide
    DME0001    XEOTICID    XEO00001    MOACRIVE    Induction

Each file opens with a human-readable header/abbreviations block; data rows
are recognized by starting with an ID matching ``DME\\d+``.
"""
import csv
import os
import re

from biothings.utils.dataload import dict_sweep, unlist

_DME_ID_RE = re.compile(r"^DME\d+$")


def _iter_data_rows(path):
    """Yield tab-split rows from an INTEDE long-format .txt file, skipping
    the header/abbreviations block that precedes the actual data."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            row = line.split("\t")
            if _DME_ID_RE.match(row[0]):
                yield row


def _get_entity(entities, dme_id):
    return entities.setdefault(dme_id, {"dme_id": dme_id})


def _load_xref(path, entities):
    """P2-04-1-INTEDE_DME_Cross_Matching_ID.txt — top-level attrs only."""
    field_map = {
        "DME_NAME": "name",
        "SPESNAME": "species",
        "UNIPROID": "uniprot",
        "GENE__ID": "gene_id",
        "ECNUMBER": "ec_number",
    }
    for row in _iter_data_rows(path):
        if len(row) < 3:
            continue
        dme_id, key, value = row[0], row[1], row[2]
        entity = _get_entity(entities, dme_id)
        out_key = field_map.get(key)
        if out_key:
            entity[out_key] = value


def _load_xeotic(path, entities):
    """P1-02-1-INTEDE_XEOTIC_DME_Interaction.txt — nested under XEOTICID."""
    top_field_map = {"DME_NAME": "name", "SPESNAME": "species"}
    sub_field_map = {
        "XEO_NAME": "name",
        "XEO_TYPE": "type",
        "XEO_CLAS": "classification",
        "DESCRIPT": "description",
        "GENEFORM": "gene_form",
        "MOACRIVE": "modulation_type",
    }
    groups = {}  # dme_id -> {xeo_id: {fields}}
    for row in _iter_data_rows(path):
        dme_id = row[0]
        entity = _get_entity(entities, dme_id)
        if len(row) == 3:
            key, value = row[1], row[2]
            out_key = top_field_map.get(key)
            if out_key and not entity.get(out_key):
                entity[out_key] = value
        elif len(row) >= 5 and row[1] == "XEOTICID":
            xeo_id = row[2]
            key = row[3]
            value = "\t".join(row[4:])
            sub = groups.setdefault(dme_id, {}).setdefault(xeo_id, {"xeotic_id": xeo_id})
            out_key = sub_field_map.get(key)
            if out_key:
                sub[out_key] = value

    for dme_id, xeo_map in groups.items():
        entity = _get_entity(entities, dme_id)
        entity["xenobiotic_interactions"] = list(xeo_map.values())


def _load_micbio(path, entities):
    """P1-01-1-INTEDE_MICBIO_DME_Interaction.csv — standard CSV."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        for row in reader:
            dme_id = row.get("DME_ID")
            if not dme_id:
                continue
            entity = _get_entity(entities, dme_id)
            if not entity.get("name"):
                entity["name"] = row.get("Protein_Name_generally")
            if not entity.get("species"):
                entity["species"] = row.get("SpeciesName")
            entity.setdefault("microbiome_interactions", []).append(
                {
                    "drug_id": row.get("Drug_ID"),
                    "drug_name": row.get("Drug_Name"),
                    "interacted_species": row.get("Interacted_species_name"),
                    "location": row.get("Location"),
                    "result": row.get("Result"),
                }
            )


def _load_hosppi(path, entities):
    """P1-03-1-...HOSPPI...TF&Oligomerization&ncRNA&Histone_Modification.txt
    — nested under UNIPROID (protein partner) or MIRNA_ID (ncRNA partner)."""
    top_field_map = {"DME_NAME": "name", "SPESNAME": "species"}
    sub_field_map = {
        "PROTNAME": "partner_name",
        "HPPI_DIS": "disease",
        "MOFCLASS": "mof_classification",
        "MOFDETAI": "mof_detail",
        "SUBSTRAT": "substrate",
        "CELLLINE": "cell_line",
        "PPI_SUMM": "summary",
        "DESCRIPT": "description",
    }
    groups = {}  # dme_id -> {(marker, partner_id): {fields}}
    for row in _iter_data_rows(path):
        dme_id = row[0]
        entity = _get_entity(entities, dme_id)
        if len(row) == 3:
            key, value = row[1], row[2]
            out_key = top_field_map.get(key)
            if out_key and not entity.get(out_key):
                entity[out_key] = value
        elif len(row) >= 5 and row[1] in ("UNIPROID", "MIRNA_ID"):
            marker, partner_id = row[1], row[2]
            key = row[3]
            value = "\t".join(row[4:])
            group_key = (partner_id,)
            sub = groups.setdefault(dme_id, {}).setdefault(
                group_key,
                {
                    "partner_id": partner_id,
                    "partner_type": "ncRNA" if marker == "MIRNA_ID" else "protein",
                },
            )
            out_key = sub_field_map.get(key)
            if out_key:
                sub[out_key] = value

    for dme_id, partner_map in groups.items():
        entity = _get_entity(entities, dme_id)
        entity["host_protein_interactions"] = list(partner_map.values())


def _safe_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _load_methylation(path, entities):
    """P1-03-2-INTEDE_HOSPPI_DME_Interaction_DNA_Methylation.txt — nested
    under ICD_CODE, with three tissue-comparison sub-blocks (health/
    adjacent/other) each carrying a description, delta-beta, and p-value."""
    top_field_map = {"DME_NAME": "name", "SPESNAME": "species"}
    comparison_map = {
        "C_H_DNAM": ("case_vs_health", "status"),
        "C_H_DELB": ("case_vs_health", "delta_beta"),
        "C_H_PVAL": ("case_vs_health", "pvalue"),
        "C_A_DNAM": ("case_vs_adjacent", "status"),
        "C_A_DELB": ("case_vs_adjacent", "delta_beta"),
        "C_A_PVAL": ("case_vs_adjacent", "pvalue"),
        "C_O_DNAM": ("case_vs_other", "status"),
        "C_O_DELB": ("case_vs_other", "delta_beta"),
        "C_O_PVAL": ("case_vs_other", "pvalue"),
    }
    groups = {}  # dme_id -> {icd_code: {fields}}
    for row in _iter_data_rows(path):
        dme_id = row[0]
        entity = _get_entity(entities, dme_id)
        if len(row) == 3:
            key, value = row[1], row[2]
            out_key = top_field_map.get(key)
            if out_key and not entity.get(out_key):
                entity[out_key] = value
        elif len(row) >= 5 and row[1] == "ICD_CODE":
            icd_code = row[2]
            key = row[3]
            value = "\t".join(row[4:])
            sub = groups.setdefault(dme_id, {}).setdefault(
                icd_code, {"icd_code": icd_code}
            )
            if key == "DIS_NAME":
                sub["disease_name"] = value
            elif key in comparison_map:
                comparison, field = comparison_map[key]
                block = sub.setdefault(comparison, {})
                block[field] = _safe_float(value) if field in ("delta_beta", "pvalue") else value

    for dme_id, icd_map in groups.items():
        entity = _get_entity(entities, dme_id)
        entity["methylation_interactions"] = list(icd_map.values())


def load_data(data_folder):
    """Parse INTEDE bulk files and yield one BioThings document per DME."""
    entities = {}

    xref_file = os.path.join(data_folder, "P2-04-1-INTEDE_DME_Cross_Matching_ID.txt")
    xeotic_file = os.path.join(data_folder, "P1-02-1-INTEDE_XEOTIC_DME_Interaction.txt")
    micbio_file = os.path.join(data_folder, "P1-01-1-INTEDE_MICBIO_DME_Interaction.csv")
    hosppi_file = os.path.join(
        data_folder,
        "P1-03-1-INTEDE_HOSPPI_DME_Interaction_TF&Oligomerization&ncRNA&Histone_Modification.txt",
    )
    methylation_file = os.path.join(
        data_folder, "P1-03-2-INTEDE_HOSPPI_DME_Interaction_DNA_Methylation.txt"
    )

    for path in [xref_file, xeotic_file, micbio_file, hosppi_file, methylation_file]:
        assert os.path.exists(path), f"Expected file not found: {path}"

    _load_xref(xref_file, entities)
    _load_xeotic(xeotic_file, entities)
    _load_micbio(micbio_file, entities)
    _load_hosppi(hosppi_file, entities)
    _load_methylation(methylation_file, entities)

    for dme_id, fields in entities.items():
        doc = {
            "_id": dme_id,
            "intede": fields,
        }
        doc = dict_sweep(unlist(doc), [None, "", []])
        yield doc
